### ISSUE TITLE
[suggestion] add loader just to corners

### ISSUE THREAD

**Issue by ftonato** [raphaelfabeni/css-loader#39]
Hello @raphaelfabeni, how are you?

First, congratulations for your effort to keep on this project.

I would like to suggest an idea about loader border.
For now, exist an example to `loader border`, but I think it's important able to run loader just on corner of page (top, right, bottom, left)...

I edited your `loaders/_loader-border.sass` file's and this is my ~poor~ implementation of (loader corner `top`):

```scss
@keyframes corners 
  6%
    width: $loader-border--width * 4
    height: $loader-border--height

  25%
    width: $loader-border--width
    height: $loader-border--height
    left: calc(100% - #{$loader-border--width})

  50%
    height: $loader-border--height
    left: calc(100% - #{$loader-border--width})

  75%
    width: $loader-border--width
    left: 0
```

See it bellow...
![loader-border](https://user-images.githubusercontent.com/5417662/41691365-9ba1517e-74d0-11e8-82d4-89c0992c4f5a.gif)
